#!/bin/bash
##############################################
# Script for installing items on a Darwin
#  (Mac OS) machine
##############################################
#############
# GLOBALS
#############

#############
# FUNCTIONS
#############
# Installs Command Line Tools programmatically
# See https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line
install_clt () {
  touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress;
  PROD=$(softwareupdate -l |
      grep "\*.*Command Line" |
      head -n 1 | awk -F"*" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n')
  softwareupdate -i "$PROD" --verbose;
}

# Installs Homebrew
install_brew () {
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
}

############
# MAIN
############
install_clt
install_brew

# Uses homebrew / cask to install all needed libraries in Mac
brew bundle