#!/bin/bash
##############################################
# Script for installing items on a Darwin
#  (Mac OS) machine
##############################################
#############
# GLOBALS
#############

#############
# FUNCTIONS
#############
# Installs Command Line Tools programmatically
# See https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line
install_clt () {
  if ! xcode-select -p 1>/dev/null; then
    echo "  Command Line Tools not installed - installing now"
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    PROD=$(softwareupdate -l |
      grep "\*.*Command Line" |
      head -n 1 | awk -F"*" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n')
    softwareupdate -i "$PROD" --verbose
  fi
}

# Installs Homebrew
install_brew () {
  if ! which brew 1>/dev/null; then
    echo "  Brew not installed - installing now"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

# Prints out a message after installations are done denoting what was *not* installed
print_message() {
  applist=(
    'Wunderlist'
  )

  echo "  These apps are not installable through Brew. Install them manually:\n"

  for i in "${applist[@]}"; do
    echo "    - $i"
  done
}
############
# MAIN
############
install_clt
install_brew
print_message

# Uses homebrew / cask to install all needed libraries in Mac
brew bundle

