#!/bin/bash
##############################################
# Script for installing items on a Darwin
#  (Mac OS) machine
##############################################
#############
# GLOBALS
#############

#############
# FUNCTIONS
#############
# Installs Command Line Tools programmatically
# See https://apple.stackexchange.com/questions/107307/how-can-i-install-the-command-line-tools-completely-from-the-command-line
install_clt() {
  if ! xcode-select -p 1>/dev/null; then
    echo "  Command Line Tools not installed - installing now"
    touch /tmp/.com.apple.dt.CommandLineTools.installondemand.in-progress
    PROD=$(softwareupdate -l |
      grep "\*.*Command Line" |
      head -n 1 | awk -F"*" '{print $2}' |
      sed -e 's/^ *//' |
      tr -d '\n')
    softwareupdate -i "$PROD" --verbose
  fi
}

# Installs Homebrew
install_brew() {
  if ! which brew 1>/dev/null; then
    echo "  Brew not installed - installing now"
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  fi
}

# Moves the init.vim file to the correct directory
# and also downloads vim-plug
install_nvim_init() {
  mkdir -p ~/.config/nvim
  cp init.vim ~/.config/nvim/
  curl -fLo ~/.config/nvim/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
}

# Installs items manually through the app store using mas (Mac App Store CLI tool - https://github.com/mas-cli/mas)
install_app_store() {
  applist=(
    585829637 # Todoist
  )

  for i in "${applist[@]}"; do
    mas install $i
  done
}

############
# MAIN
############
install_clt
install_brew
install_nvim_init
brew bundle # Uses homebrew/cask to install stuff in Brewfile
install_app_store

