#!/bin/bash
##############################################
# Specifies packages to be installed for a linux
#  distribution.
##############################################

PACKAGES=(
    git # Git version control
    tmux # Terminal multiplexor
    zsh # Zsh
    curl # Curl utility
    wget # Wget utility
    gnome-tweak-tool # For tweaking stuff
    unity-tweak-tool # For tweaking stuff
    google-chrome-stable # Google Chrome
    ubuntu-restricted-extras # Media codecs
    redshift # Like f.lux
    htop # See core processing
    vagrant # Install vagrant for VM & testing
    xclip # Linux equivalent of pbcopy/pbpaste
    bleachbit # Linux equivalent of CCleaner
    wine-stable # Cleanly integrate windows apps into Linux
)

FUNCTIONS=(
    install_tmate
    install_ohmyzsh
    install_fzf
)

# Install tmate, a remote SSH pairing / terminal sharing client built on top of tmux
# https://tmate.io/
install_tmate() {
    sudo apt-get install software-properties-common
    sudo add-apt-repository ppa:tmate.io/archive
    sudo apt-get update
    sudo apt-get install tmate-nightly -y
}

# Install oh-my-zsh
# https://github.com/robbyrussell/oh-my-zsh
install_ohmyzsh() {
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
}

# Install Fuzzy file finder
# https://github.com/junegunn/fzf
install_fzf() {
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
}

